baseURL = "http://example.com/"
languageCode = "en-us"
title = "KomPect"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Nikhil Samant"
    description = "A simple image compressor powered by Imagemin"
    headerTitle = "KomPect"
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    copyright = "MIT Licence"
    ProfilePic = "AppLogo_200x200.png"
    WindowsDownload = ""
    LinuxDownload = ""
    MacDownload = ""

[[menu.main]]
    url = "/"
    name = "home"
    weight = 1

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 4
